# Configuration

#Grainfather addresse. Anvned simple_scanner til at finde.
gfaddr="BB:A0:50:04:1F:33"

#Adresse til MQTT
mqtt_ip="192.168.1.3"

#Antal sekunder mellem at der sendes til mqtt 
#selv om GF poster data hvert sekund
mqtt_delay=15

#Logging
log_level="INFO"